spring:
  profiles:
    active:
    - dev
---
server:
  port: 80

spring:
  profiles: dev
  application: 
    name: microservicecloud-config-client
      
feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false

