mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.tzhtry.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka



spring:
  application:
    name: microservicecloud-dept
  

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

eureka:
  instance:
    instance-id: microservicecloud-dept8001
spring:
  profiles:8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
---
server:
  port: 8003

eureka:
  instance:
    instance-id: microservicecloud-dept8003
spring:
  profiles:8003
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200